### ISSUE TITLE
It doesn’t update my styles with Tailwind UI

### ISSUE THREAD

**Issue by fredriksundstrom** [jerriclynsjohn/svelte-storybook-tailwind#10]
Hey! Great work with this, it helped us a lot. We found out it doesn’t update our styles in the correct way, though.

We are using Tailwind UI as a plugin, but anything we put in Storybook for it doesn’t update unless we close and start yarn stories one time.

Do you have any idea what I need to do to achieve this to update in the correct way?

I’ve tried plugins: [require('@tailwindcss/ui')], in tailwind.config.js and I’ve tried it in postcss.config.js as well, without any luck.

Thanks!

**Comment by jerriclynsjohn** [comment]
Can you share me your repo (partial), to recreate the problem.

**Comment by danielquintero** [comment]
@fredriksundstrom @jerriclynsjohn I think the issue has to do with the regex in `postcss.config.js`

before:
`const regExp = new RegExp(/[A-Za-z0-9-_:/]+/g);`
after:
`const regExp = new RegExp(/[\w-/.:]+(?<!:)/g);`

worked for me and got all the new styles provided by tailwind/ui working!
cheers.

**Comment by jerriclynsjohn** [comment]
Looking into this now and will push an update soon.

**Comment by jerriclynsjohn** [comment]
I hope these issues are updated using PR #17
