### ISSUE TITLE
Fresh Install `yarn dev` invalid token

### ISSUE THREAD

**Issue by corepay** [jerriclynsjohn/svelte-storybook-tailwind#11]
Followed instructions for build using node 12.x and 13.x

* `npx degit jerriclynsjohn/svelte-storybook-tailwind my-project`
* `yarn`
* `yarn dev`

build success -> `localhost:5000` gets console error
![image](https://user-images.githubusercontent.com/48992923/79689394-90ea6200-8222-11ea-8daa-9c104191a499.png)

FYI Terminal shows this warning but don't think this has to do with invalid token:
![image](https://user-images.githubusercontent.com/48992923/79689431-cee78600-8222-11ea-9d16-c9e9aaaffb9d.png)

**Comment by corepay** [comment]
PS removed both components fmor app.svelte and rebuild with same console error invalid token.

**Comment by jerriclynsjohn** [comment]
Checking into these now, will push update soon.

**Comment by jerriclynsjohn** [comment]
I hope all of these are solved with PR #17
