### ISSUE TITLE
Styles are missing

### ISSUE THREAD

**Issue by JakubBlaha** [jerriclynsjohn/svelte-storybook-tailwind#12]
After setting up a clean project, some of the styles are not being included. An example would be the OutlineButton, which looks different than in the demo.

![image](https://user-images.githubusercontent.com/28687156/95691055-7c5cb480-0c1c-11eb-9b26-5c54fbd53e5d.png)

> OutlineButton in live demo.

![image](https://user-images.githubusercontent.com/28687156/95691065-94343880-0c1c-11eb-8e2e-15708d6ab80a.png)

> OutlineButton after setting up a clean project.

I think a possible cause of this is that the svelte style tags are not being included.

**Comment by Isaac-Tait** [comment]
Would you mind if I took a stab at this?

**Comment by jerriclynsjohn** [comment]
Looking into these now, will push a major update fixing everything and updating all packages

**Comment by jerriclynsjohn** [comment]
I hope these are fixed with the latest update in the repo
