### ISSUE TITLE
Controls for components not present and custom decorators not working

### ISSUE THREAD

**Issue by PriyavKaneria** [jerriclynsjohn/svelte-storybook-tailwind#15]
Custom decorators do not work as per documentation [here](https://storybook.js.org/docs/svelte/writing-stories/decorators)
Also args do not form controls as they should as mentioned [here](https://storybook.js.org/docs/svelte/writing-stories/args)
Is there support for Args as well as Decorators?

btw - Nice template for storybook svelte and tailwind

**Comment by jerriclynsjohn** [comment]
I have updated the repo with the latest updates please do check and let me know if these works. I'm closing this issue for now.
