### ISSUE TITLE
Demo page shows error

### ISSUE THREAD

**Issue by sisou** [jerriclynsjohn/svelte-storybook-tailwind#2]
This is actually pretty funny.

When I first came across this project from Svelte's Twitter on my phone, I opened the link to the demo storybook and was immediately greeted by an error: "Holy smokes! Something seriously bad happened."

So I closed the page, thinking that the storybook doesn't work.

I now just opened it on my laptop to check it out again, and I just now realized that the error is actually already the demo. It's just that it's the demo of an alert! :laughing: 

So my suggestion is to change to landing page of the demo storybook to something that doesn't suggest it's broken :wink:

**Comment by jerriclynsjohn** [comment]
Noted!

**Comment by sisou** [comment]
Hi. I don't know if you plan to actually change the behavior or see it as a non-issue, but I still see the alert as the first thing when opening the demo link.

**Comment by jerriclynsjohn** [comment]
@sisou This is done, do take a look at it now
