### ISSUE TITLE
Is rollup needed? It's not in SvelteKit anymore

### ISSUE THREAD

**Issue by bostondevin** [jerriclynsjohn/svelte-storybook-tailwind#20]
Just wondering if you still need rollup since they removed it as a dependency in sveltekit.

Thanks for making this starter!

**Comment by GiorgosK** [comment]
I think this project does not integrate with sveltekit, it started before sveltekit was released and it has stayed independent of it.  Indeed it would be a great improvement to have sveltekit integrated into it.

**Comment by jerriclynsjohn** [comment]
I will create another repo with SvelteKit, I've updated this repo with Svelte + Vite
