### ISSUE TITLE
svelte + tailwindcss with webpack

### ISSUE THREAD

**Issue by debugpoint136** [jerriclynsjohn/svelte-storybook-tailwind#8]
Do you mind pointing me to a simple svelte + tailwindcss starter project that uses webpack instead of rollup? Thanks!

**Comment by jerriclynsjohn** [comment]
I can try providing this template in a new repo. Give me sometime

**Comment by brend8c** [comment]
Can I take a look at the finished sample site?
Which was done on this assembly.
